=== rms1000watt/hello-world-typescript/app/route/pizza/pizza-tjs.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "Destination": {
            "enum": [
                "delivery",
                "pickup"
            ],
            "type": "string"
        },
        "OrderType": {
            "enum": [
                "phone",
                "website"
            ],
            "type": "string"
        },
        "Size": {
            "enum": [
                "L",
                "M",
                "S",
                "XL"
            ],
            "type": "string"
        }
    },
    "properties": {
        "customerID": {
            "maximum": 999999999,
            "minimum": 0,
            "type": "integer"
        },
        "destination": {
            "$ref": "#/definitions/Destination"
        },
        "orderID": {
            "maximum": 999999999,
            "minimum": 0,
            "type": "integer"
        },
        "orderType": {
            "$ref": "#/definitions/OrderType"
        },
        "promotion": {
            "type": "string"
        },
        "size": {
            "$ref": "#/definitions/Size"
        },
        "toppings": {
            "items": {
                "enum": [
                    "anchovy",
                    "bacon",
                    "ham",
                    "jalepeno",
                    "olive",
                    "pepperoni",
                    "pineapple",
                    "sausage"
                ],
                "type": "string"
            },
            "type": "array"
        }
    },
    "required": [
        "customerID",
        "destination",
        "orderID",
        "orderType",
        "size",
        "toppings"
    ],
    "type": "object"
}

=== rms1000watt/hello-world-typescript/app/fixture/pizza.json
[
  {
    "orderID": 0,
    "customerID": 4910,
    "toppings": [
      "pepperoni",
      "olive"
    ],
    "size": "L",
    "orderType": "phone",
    "destination": "pickup"
  },
  {
    "orderID": 1,
    "customerID": 33312,
    "toppings": [
      "ham",
      "pineapple"
    ],
    "size": "S",
    "orderType": "website",
    "destination": "delivery"
  },
  {
    "orderID": 2,
    "customerID": 818282,
    "toppings": [
      "anchovy",
      "jalepeno"
    ],
    "size": "M",
    "orderType": "phone",
    "destination": "pickup"
  },
  {
    "orderID": 3,
    "customerID": 999,
    "toppings": [
      "pepperoni",
      "bacon"
    ],
    "size": "L",
    "orderType": "phone",
    "destination": "delivery"
  }
]
